### ISSUE TITLE
Orphan pruning is not working

### ISSUE THREAD

**Issue by dwyeraidan** [Notifiarr/dockwatch#47]
I've noticed that the scheduled orphan prune run is not working for me.

I have prune set at 16:00, which should run daily.

Instead in logs I see this happen : migration 003 has not been applied

```
4122 | 2024-11-01 3:00:00 [INFO] functions/crons.php LN: 82 :: Cron: skipped, frequency setting will run at hour 16
4123 | 2024-11-01 3:00:00 [INFO] functions/crons.php LN: 83 :: run <-
4124 | 2024-11-01 4:00:00 [INFO] crons/prune.php LN: 16 :: run ->
4125 | 2024-11-01 4:00:00 [INFO] functions/crons.php LN: 90 :: Cron cancelled: migration 003 has not been applied
```

This is my docker compose file.

```
services:
  dockwatch:
    container_name: dockwatch
    image: ghcr.io/notifiarr/dockwatch:main
    restart: unless-stopped
    ports:
      - 9999:80/tcp
    environment:
      #-DOCKER_HOST=127.0.0.1:2375 # Uncomment and adjust accordingly if you use a socket proxy
      - PUID=1001
      - PGID=996
      - TZ=Australia/Brisbane
    volumes:
      - /root/docker-apps/dockwatch/config:/config
      - /var/run/docker.sock:/var/run/docker.sock # Comment this line if you use a socket proxy
```

Have I done something wrong?
Thanks.
