### ISSUE TITLE
API stats for other servers

### ISSUE THREAD

**Issue by robflate** [Notifiarr/dockwatch#57]
Is there an API endpoint that shows the `uptodate` and `outdated` info for containers on other servers that are added to Dockwatch?

I use [Homepage](https://gethomepage.dev/widgets/services/customapi/) and pull data from the Dockwatch API to show `uptodate` and `outdated` containers in a widget using;

```
    - Dockwatch:
        icon: sh-dockwatch
        href: https://dockwatch.{{HOMEPAGE_VAR_DOMAINNAME_INT}}
        description: Container updater
        server: htpc-docker
        container: dockwatch
        widget:
          type: customapi
          url: http://dockwatch:80/api/stats/overview&apikey={{HOMEPAGE_VAR_DOCKWATCH_API_KEY}}
          mappings:
            - field:
                response:
                  updates: uptodate
              label: Up to date
            - field:
                response:
                  updates: outdated
              label: Outdated
```
This only shows stats for the main instance, not other servers. Thanks.
